name: Create Packages and Release

#on:
#  push:
#    tags:
#      - '*'
on:
  push:
      branches:
        - main  # Change this to your default branch name

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Prepare Debian package directory
        run: |
          mkdir -p deb-package/DEBIAN
          echo "Package: my-python-app" >> deb-package/DEBIAN/control
          echo "Version: 1.0" >> deb-package/DEBIAN/control
          echo "Architecture: all" >> deb-package/DEBIAN/control
          echo "Maintainer: Your Name <your.email@example.com>" >> deb-package/DEBIAN/control
          echo "Description: My Python App" >> deb-package/DEBIAN/control

          mkdir -p deb-package/usr/bin
          cp turnin.py deb-package/usr/bin
          chmod +x deb-package/usr/bin/turnin.py

          echo "#!/bin/bash" > deb-package/DEBIAN/postinst
          echo "pip install -r /usr/bin/turnin.py/requirements.txt" >> deb-package/DEBIAN/postinst
          chmod +x deb-package/DEBIAN/postinst

      - name: Create my-package.spec
        run: |
          echo "Name: my-package" > my-package.spec
          echo "Version: 1.0" >> my-package.spec
          echo "Release: 1%{?dist}" >> my-package.spec
          echo "Summary: My RPM Package" >> my-package.spec
          echo "License: MIT" >> my-package.spec
          echo "URL: https://github.com/your-username/your-repo" >> my-package.spec
          echo "Source0: %{name}-%{version}.tar.gz" >> my-package.spec
          echo "" >> my-package.spec
          echo "%description" >> my-package.spec
          echo "This is an example RPM package." >> my-package.spec
          echo "" >> my-package.spec
          echo "%prep" >> my-package.spec
          echo "%setup -q -c -n %{name}-%{version}" >> my-package.spec
          echo "" >> my-package.spec
          echo "%install" >> my-package.spec
          echo "rm -rf %{buildroot}" >> my-package.spec
          echo "mkdir -p %{buildroot}/usr/bin" >> my-package.spec
          echo "cp turnin.py %{buildroot}/usr/bin/" >> my-package.spec
          echo "chmod +x %{buildroot}/usr/bin/turnin.py" >> my-package.spec
          echo "" >> my-package.spec
          echo "%files" >> my-package.spec
          echo "%defattr(-,root,root,-)" >> my-package.spec
          echo "/usr/bin/turnin.py" >> my-package.spec
          echo "" >> my-package.spec
          echo "%changelog" >> my-package.spec
          echo "* Mon Aug 21 2023 Your Name <your.email@example.com> - 1.0-1" >> my-package.spec
          echo "- Initial package" >> my-package.spec

      - name: Create source archive
        run: |
          tar czvf my-package-1.0.tar.gz deb-package

      - name: Prepare RPM build directory
        run: |
          mkdir -p ~/rpmbuild/SOURCES
          cp my-package-1.0.tar.gz ~/rpmbuild/SOURCES/

      - name: Build RPM package
        run: |
          rpmbuild -bb my-package.spec

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./deb-package.deb
            ~/rpmbuild/RPMS/noarch/my-package-1.0-1.noarch.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
