name: Build macOS Package

on:
  push:
    branches:
      - master

jobs:
  build-macos-package:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt  # Install all dependencies from requirements.txt

      - name: Build macOS App
        run: |
          pyinstaller --onefile turnin.py  # Replace with the actual name of your Python script

      - name: Create App Bundle
        run: |
          mkdir -p TurnIn.app/Contents/MacOS
          mv dist/turnin TurnIn.app/Contents/MacOS
          cp cse.logo.png TurnIn.app/Contents/Resources

          # Create Info.plist
          echo '<?xml version="1.0" encoding="UTF-8"?>' > TurnIn.app/Contents/Info.plist
          echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> TurnIn.app/Contents/Info.plist
          echo '<plist version="1.0">' >> TurnIn.app/Contents/Info.plist
          echo '<dict>' >> TurnIn.app/Contents/Info.plist
          echo '    <key>CFBundleDevelopmentRegion</key>' >> TurnIn.app/Contents/Info.plist
          echo '    <string>English</string>' >> TurnIn.app/Contents/Info.plist
          echo '    <key>CFBundleExecutable</key>' >> TurnIn.app/Contents/Info.plist
          echo '    <string>turnin</string>' >> TurnIn.app/Contents/Info.plist
          echo '    <key>CFBundleGetInfoString</key>' >> TurnIn.app/Contents/Info.plist
          echo '    <string>TurnIn App</string>' >> TurnIn.app/Contents/Info.plist
          echo '    <key>CFBundleIconFile</key>' >> TurnIn.app/Contents/Info.plist
          echo '    <string>cse.logo</string>' >> TurnIn.app/Contents/Info.plist
          echo '    <key>CFBundleIdentifier</key>' >> TurnIn.app/Contents/Info.plist
          echo '    <string>net.orfanidis.TurnIn</string>' >> TurnIn.app/Contents/Info.plist
          echo '    <key>CFBundleInfoDictionaryVersion</key>' >> TurnIn.app/Contents/Info.plist
          echo '    <string>6.0</string>' >> TurnIn.app/Contents/Info.plist
          echo '    <key>CFBundleName</key>' >> TurnIn.app/Contents/Info.plist
          echo '    <string>TurnIn</string>' >> TurnIn.app/Contents/Info.plist
          echo '    <key>CFBundlePackageType</key>' >> TurnIn.app/Contents/Info.plist
          echo '    <string>APPL</string>' >> TurnIn.app/Contents/Info.plist
          echo '    <key>CFBundleShortVersionString</key>' >> TurnIn.app/Contents/Info.plist
          echo '    <string>3.0</string>' >> TurnIn.app/Contents/Info.plist
          echo '    <key>CFBundleSignature</key>' >> TurnIn.app/Contents/Info.plist
          echo '    <string>????</string>' >> TurnIn.app/Contents/Info.plist
          echo '    <key>CFBundleVersion</key>' >> TurnIn.app/Contents/Info.plist
          echo '    <string>3.0</string>' >> TurnIn.app/Contents/Info.plist
          echo '    <key>CSResourcesFileMapped</key>' >> TurnIn.app/Contents/Info.plist
          echo '    <true/>' >> TurnIn.app/Contents/Info.plist
          echo '    <key>NSAppleScriptEnabled</key>' >> TurnIn.app/Contents/Info.plist
          echo '    <true/>' >> TurnIn.app/Contents/Info.plist
          echo '    <key>NSHumanReadableCopyright</key>' >> TurnIn.app/Contents/Info.plist
          echo '    <string>© 2023 orfanidis.net.gr</string>' >> TurnIn.app/Contents/Info.plist
          echo '    <key>NSPrincipalClass</key>' >> TurnIn.app/Contents/Info.plist
          echo '    <string>NSApplication</string>' >> TurnIn.app/Contents/Info.plist
          echo '</dict>' >> TurnIn.app/Contents/Info.plist
          echo '</plist>' >> TurnIn.app/Contents/Info.plist

      - name: Create DMG Installer
        run: |
          hdiutil create -srcfolder TurnIn.app -volname TurnIn turnin.dmg

      - name: Upload DMG Installer
        uses: actions/upload-artifact@v2
        with:
          name: turnin.dmg
          path: turnin.dmg
