name: Create Debian Package and Push to Repository

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Prepare Debian package directory
        run: |
          mkdir -p deb-package/DEBIAN
          echo "Package: turnin" >> deb-package/DEBIAN/control
          echo "Version: 1.0" >> deb-package/DEBIAN/control
          echo "Architecture: all" >> deb-package/DEBIAN/control
          echo "Maintainer: Pavlos Orfanidis <pavlos@orfanidis.net.gr>" >> deb-package/DEBIAN/control
          echo "Description: TurnIn App" >> deb-package/DEBIAN/control

          mkdir -p deb-package/usr/bin
          cp turnin.py deb-package/usr/bin
          chmod +x deb-package/usr/bin/turnin.py

          mkdir -p deb-package/usr/share/applications
          echo "[Desktop Entry]" >> deb-package/usr/share/applications/turnin.desktop
          echo "Name=TurnIn" >> deb-package/usr/share/applications/turnin.desktop
          echo "Exec=python3 /usr/bin/turnin.py" >> deb-package/usr/share/applications/turnin.desktop
          echo "Icon=/usr/share/icons/cse.logo.png" >> deb-package/usr/share/applications/turnin.desktop
          echo "Type=Application" >> deb-package/usr/share/applications/turnin.desktop

          mkdir -p deb-package/usr/share/icons
          cp cse.logo.png deb-package/usr/share/icons

      - name: Create post-install script
        run: |
          echo "#!/bin/bash" > deb-package/DEBIAN/postinst
          echo "pip install -r /usr/bin/turnin.py/requirements.txt" >> deb-package/DEBIAN/postinst
          chmod +x deb-package/DEBIAN/postinst

      - name: Build Debian package
        run: |
          dpkg-deb --build deb-package

      - name: Push package to repository
        run: |
          git config --local user.email "pavlos@orfanidis.net.gr"
          git config --local user.name "Pavlos Orfanidis"
          git add deb-package.deb
          git commit -m "Add TurnIn deb package"
          git push origin HEAD
