name: Create Debian Package

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Prepare Debian package directory
        run: |
          mkdir -p deb-package/DEBIAN
          echo "Package: turnin" >> deb-package/DEBIAN/control
          echo "Version: 1.0" >> deb-package/DEBIAN/control
          echo "Architecture: all" >> deb-package/DEBIAN/control
          echo "Maintainer: Pavlos Orfanidis <pavlos@orfanidis.net.gr>" >> deb-package/DEBIAN/control
          echo "Description: TurnIn App" >> deb-package/DEBIAN/control
          echo "Depends: python3-sshtunnel, python3-paramiko, python3-sentry-sdk, python3-pyqt5" >> deb-package/DEBIAN/control  # Specify dependencies

          mkdir -p deb-package/usr/bin
          cp turnin.py deb-package/usr/bin
          chmod +x deb-package/usr/bin/turnin.py

          mkdir -p deb-package/usr/share/applications
          echo "[Desktop Entry]" >> deb-package/usr/share/applications/turnin.desktop
          echo "Name=TurnIn" >> deb-package/usr/share/applications/turnin.desktop
          echo "Exec=python3 /usr/bin/turnin.py" >> deb-package/usr/share/applications/turnin.desktop
          echo "Icon=/usr/share/icons/cse.logo.png" >> deb-package/usr/share/applications/turnin.desktop
          echo "Type=Application" >> deb-package/usr/share/applications/turnin.desktop

          mkdir -p deb-package/usr/share/icons
          cp cse.logo.png deb-package/usr/share/icons
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v2
        with:
          name: deb-package.deb
          path: deb-package.deb
