name: Build RPM Package on CentOS

on:
  push:
    branches:
      - master

jobs:
  build-rpm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-build@v2

      - name: Build RPM in Docker
        run: |
          docker run --rm -v $PWD:/src centos:8 /bin/bash -c "
            dnf install -y rpm-build
            cd /src
            mkdir -p rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}

            # Create the RPM spec file
            echo 'Name: turnin' > rpmbuild/SPECS/turnin.spec
            echo 'Version: 1.0' >> rpmbuild/SPECS/turnin.spec
            echo 'Release: 1' >> rpmbuild/SPECS/turnin.spec
            echo 'Summary: TurnIn App' >> rpmbuild/SPECS/turnin.spec
            echo 'License: MIT' >> rpmbuild/SPECS/turnin.spec
            echo 'BuildRequires: python3-sshtunnel python3-paramiko python3-sentry-sdk python3-pyqt5 python3-pyinstaller' >> rpmbuild/SPECS/turnin.spec
            echo '' >> rpmbuild/SPECS/turnin.spec
            echo '%description' >> rpmbuild/SPECS/turnin.spec
            echo 'TurnIn App' >> rpmbuild/SPECS/turnin.spec
            echo '' >> rpmbuild/SPECS/turnin.spec
            echo '%prep' >> rpmbuild/SPECS/turnin.spec
            echo '' >> rpmbuild/SPECS/turnin.spec
            echo '%install' >> rpmbuild/SPECS/turnin.spec
            echo 'mkdir -p %{buildroot}/usr/bin' >> rpmbuild/SPECS/turnin.spec
            echo 'cp turnin.py %{buildroot}/usr/bin/' >> rpmbuild/SPECS/turnin.spec
            echo 'chmod +x %{buildroot}/usr/bin/turnin.py' >> rpmbuild/SPECS/turnin.spec
            echo '' >> rpmbuild/SPECS/turnin.spec
            echo '%files' >> rpmbuild/SPECS/turnin.spec
            echo '%defattr(-,root,root)' >> rpmbuild/SPECS/turnin.spec
            echo '/usr/bin/turnin.py' >> rpmbuild/SPECS/turnin.spec

            # Copy source files
            cp turnin.py rpmbuild/SOURCES/

            # Build the RPM package
            rpmbuild -ba rpmbuild/SPECS/turnin.spec
          "

      - name: Copy RPM artifacts
        run: |
          cp rpmbuild/RPMS/*/*.rpm .

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v2
        with:
          name: rpms
          path: ./*.rpm
