name: Build RPM Package on CentOS

on:
  push:
    branches:
      - master

jobs:
  build-rpm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build RPM in Docker
        run: |
          docker buildx build --file Dockerfile.rpmbuild --output type=local,dest=. .

      - name: Copy RPM artifacts
        run: cp ./*.rpm .

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v2
        with:
          name: rpms
          path: ./*.rpm
